name: Run Simple Python Script

on: [push]

jobs:
  run:
    runs-on: sel-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Python script
        run: python 1.py
